export const CHANGE_TAB = 'CHANGE_TAB';

export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';

export const FETCH_VACCINE_DATA_REQUEST = 'FETCH_VACCINE_DATA_REQUEST';
export const FETCH_VACCINE_DATA_SUCCESS = 'FETCH_VACCINE_DATA_SUCCESS';
export const FETCH_VACCINE_DATA_FAILURE = 'FETCH_VACCINE_DATA_FAILURE';

export const CHANGE_VACCINE_STATUS_REQUEST = 'CHANGE_VACCINE_STATUS_REQUEST';
export const CHANGE_VACCINE_STATUS_FAILURE = 'CHANGE_VACCINE_STATUS_FAILURE';